//
// Created by admin1 on 2023/1/4.
//

#ifndef APP_COMMUNICATION_SELFCHECKERRORTYPE_H
#define APP_COMMUNICATION_SELFCHECKERRORTYPE_H

enum SelfCheckErrorType {
    //move_base
    GLOBAL_PLANNER_CREATE_FAILED,
    LOCAL_PLANNER_CREATE_FAILED,
    ILLEGAL_QUATERNION,
    GLOBAL_COST_MAP_GET_FAILED,
    GET_CURRENT_POSE_FAILED,
    GLOBAL_PLAN_FAILED,
    SET_LOCAL_PLAN_FAILED,
    LOCAL_CONTROL_FAILED,
    PLANNING_RECOVERY_FAILED_AND_SKIP,
    LOCAL_CONTROL_FAILED_AND_SKIP,
    OSCILLATION_RECOVERY_FAILED_AND_SKIP,
    SONAR_RECOVERY_FAILED_AND_SKIP,
    PROHIBITION_RECOVERY_FAILED_AND_SKIP,
    SONAR_RECOVERY_TIME_OUT,

    //sensor
    CAMERA1_NO_DATA,
    CAMERA2_NO_DATA,
    IMU_NO_DATA,
    ODOM_NO_DATA,
    LASER_NO_DATA,
    ULTRASONIC1_ABNORMAL_OVER_30_SECOND,
    ULTRASONIC2_ABNORMAL_OVER_30_SECOND,
    BUMP1_ABNORMAL_OVER_30_SECOND,
    BUMP2_ABNORMAL_OVER_30_SECOND,
    BUMP3_ABNORMAL_OVER_30_SECOND,
    BUMP4_ABNORMAL_OVER_30_SECOND,
    BMS_HOP,
    TRACKED_POSE_HOP,
    BIAS_DETECTED,

    //back_charge
    NOT_AT_BASE_POINT,
    OUT_STATION_ERROR,

    //soft_ware
    SOFTWARE_INTERRUPT,
    //laser_restart
    LASER_RESTART_START,
    LASER_RESTART_SUCCEED,
    LASER_RESTART_FAILED,
    //hls_error
    HLS_ERROR
};

#endif //APP_COMMUNICATION_SELFCHECKERRORTYPE_H
