//
// Created by Looper on 2022/12/8.
//

#include "clean_history/CleanHistoryVo.h"

clean_history_db::CleanHistoryVo::CleanHistoryVo(const std::string &taskId, int mode, int rate, int sweepStatus,
                                                 int mopStatus, int vacuumStatus, int pushStatus,
                                                 int aromatherapyStatus, int disinfectStatus,
                                                 const std::string &launchPeople, const std::string &timeMode,
                                                 long launchTime, long executeTime, long cleanTime, long endTime,
                                                 int cleanArea, int currentStep, int currentFrequency, int totalStep,
                                                 int totalFrequency, int historyState, int currentFlow, int urgencyStop,
                                                 int pauseNum, int manualBack, int lowPowerBack, int forceBack,
                                                 int outStation, int endSleep, int backBaseRetries,
                                                 int backBasePointArrived, int stationArrived, int rechargeRetries,
                                                 int closeMechanism, int openMechanism, int errorCode,
                                                 const std::string &errorMsg) : task_id_(taskId), mode_(mode),
                                                                                rate_(rate), sweep_status_(sweepStatus),
                                                                                mop_status_(mopStatus),
                                                                                vacuum_status_(vacuumStatus),
                                                                                push_status_(pushStatus),
                                                                                aromatherapy_status_(
                                                                                        aromatherapyStatus),
                                                                                disinfect_status_(disinfectStatus),
                                                                                launch_people_(launchPeople),
                                                                                time_mode_(timeMode),
                                                                                launch_time_(launchTime),
                                                                                execute_time_(executeTime),
                                                                                clean_time_(cleanTime),
                                                                                end_time_(endTime),
                                                                                clean_area_(cleanArea),
                                                                                current_step_(currentStep),
                                                                                current_frequency_(currentFrequency),
                                                                                total_step_(totalStep),
                                                                                total_frequency_(totalFrequency),
                                                                                history_state_(historyState),
                                                                                current_flow_(currentFlow),
                                                                                urgency_stop_(urgencyStop),
                                                                                pause_num_(pauseNum),
                                                                                manual_back_(manualBack),
                                                                                low_power_back_(lowPowerBack),
                                                                                force_back_(forceBack),
                                                                                out_station_(outStation),
                                                                                end_sleep_(endSleep),
                                                                                back_base_retries_(backBaseRetries),
                                                                                back_base_point_arrived_(
                                                                                        backBasePointArrived),
                                                                                station_arrived_(stationArrived),
                                                                                recharge_retries_(rechargeRetries),
                                                                                close_mechanism_(closeMechanism),
                                                                                open_mechanism_(openMechanism),
                                                                                error_code_(errorCode),
                                                                                error_msg_(errorMsg) {}
