//
// Created by Looper on 2022/10/19.
//

#ifndef APP_COMMUNICATION_TSP_SOLVER_DEFINES_H
#define APP_COMMUNICATION_TSP_SOLVER_DEFINES_H

enum TSPSolvers {
    TSP_NEAREST_NEIGHBOR = 1, TSP_GENETIC = 2
};

#endif //APP_COMMUNICATION_TSP_SOLVER_DEFINES_H
