//
// Created by lijiang on 2021/12/18.
//

#ifndef APP_COMMUNICATION_ABSTRACTSUBSCRIBE_H
#define APP_COMMUNICATION_ABSTRACTSUBSCRIBE_H

class AbstractSubscribe {

};

#endif //APP_COMMUNICATION_ABSTRACTSUBSCRIBE_H
